sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: '1234'

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

#  阿里云oss配置方式
#  alioss:
#    endpoint:
#    access-key-id:
#    access-key-secret:
#    bucket-name: